# Generated by Django 4.0.5 on 2022-07-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='states',
        ),
    ]
